### ISSUE TITLE
Header section: There are no sub menu created under Products and Stone Range menus.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/WA-Marble-and-Granite#1]
![image](https://cloud.githubusercontent.com/assets/11186313/9510831/be5ff688-4ca2-11e5-9fb6-aff72a1486a3.png)

**Comment by isaq-titan** [comment]
It is not considered as a bug as these are not sub menus, it is mentioned only to display the flow of the pages.

**Comment by roseliesromeo** [comment]
As part of the implementation checklist, it should be readily available before sending it for testing.  
https://knowledgebase.titanweb.com.au/implementation-practices/implementation-checklist

Everything needed in the site should be implemented not QAs to provide.
