### ISSUE TITLE
Stone range: Category without products assigned is displayed in the grid view but when clicked to open the page, Only root of the breadcrumbs is displayed.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/WA-Marble-and-Granite#100]
![image](https://cloud.githubusercontent.com/assets/11186313/9652006/ebde6ab6-5249-11e5-9edc-6a3f760584a1.png)

**Comment by isaq-titan** [comment]
Category without products assigned is hidden now.

**Comment by roseliesromeo** [comment]
I still can see them in the grid view.

**Comment by isaq-titan** [comment]
It is fixed now.
