### ISSUE TITLE
Gallery page: Distorted layout of the grid.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/WA-Marble-and-Granite#111]
http://wamarble.stage.titanweb.com.au/edge-details/nggallery/album-title-goes-here-for-two-lines-long/edge-details
![image](https://cloud.githubusercontent.com/assets/11186313/9680988/588310b6-532d-11e5-8e71-42faa80ae373.png)

**Comment by isaq-titan** [comment]
Fixed it now.
