### ISSUE TITLE
Left sidebar: Sidebar section isn't implemented as sticky sidebar.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/WA-Marble-and-Granite#19]
Applicable to other inner pages.

It is specified in the project scope and it is noted in the design PSD to use  sticky sidebar: http://spoiledmilk.com/demos/sticky-sidebar/

![image](https://cloud.githubusercontent.com/assets/11186313/9512375/bb8830ea-4cb3-11e5-8f84-208d8bab057a.png)

**Comment by isaq-titan** [comment]
Implementing Sidebar along with the load more posts is not working exactly as the javascript is unable to calculate the height of the page when load more is loading more posts than the initial posts. - Please advice

**Comment by roseliesromeo** [comment]
This has been done in some of the Titan projects.
Maybe you can refer to this site. This has both sticky sidebar and infinite scrolling implemented.  
http://bridalbentleysperth.stage.titanweb.com.au/testimonials/

**Comment by isaq-titan** [comment]
I can see that sticky sidebar isn't working in the below page, I have tested in Mozilla, Chrome and Opera.

http://bridalbentleysperth.stage.titanweb.com.au/testimonials/

Please provide me any other reference which can be helpful.

**Comment by isaq-titan** [comment]
Please advice, I am waiting for your reply.

**Comment by roseliesromeo** [comment]
Ahhh I see. The sticky sidebar in the link I gave you used to be working before the implementation was changed.  I refer this to the one who implemented it and said it is doable.

**Comment by isaq-titan** [comment]
I have fixed the sticky sidebar along with the load more, please check it and let me know your feedback.

Note: There will not be more than 8 categories displayed in the sticky sidebar because as per the given script the height of sidebar should be less than the height of the window.

**Comment by roseliesromeo** [comment]
There should be 9 categories to display in the sidebar to be consistent with the design.

**Comment by isaq-titan** [comment]
It is updated, now 9 categories are being displayed.
