### ISSUE TITLE
News page: There is no intro text (information coming soon) displayed as specified in the scope.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/WA-Marble-and-Granite#32]
![image](https://cloud.githubusercontent.com/assets/11186313/9514198/84170016-4cca-11e5-8294-b9143a70c63f.png)

![image](https://cloud.githubusercontent.com/assets/11186313/9514191/6ac5c908-4cca-11e5-9066-9ce690ee6e93.png)

**Comment by isaq-titan** [comment]
Previously we had an option of adding the content but currently the text editor is removed from the news - blog page, so it is not considered as a bug. Scope will be updated soon accordingly
