### ISSUE TITLE
News page: Shortened description isn't limited to seven lines only.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/WA-Marble-and-Granite#35]
![image](https://cloud.githubusercontent.com/assets/11186313/9514340/f26d7292-4ccb-11e5-971f-f4b0256a297d.png)

**Comment by roseliesromeo** [comment]
Still exceeds 7 lines.
![image](https://cloud.githubusercontent.com/assets/11186313/9649803/93c9fb96-522c-11e5-98bc-4a7583e54e70.png)

**Comment by roseliesromeo** [comment]
Limit post description to 7 lines for all posts, with or without featured image.

**Comment by isaq-titan** [comment]
It is fixed now.
