### ISSUE TITLE
General: Font family used doesn't adhere to what is specified in the design.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/WA-Marble-and-Granite#39]
Currently, font appears thicker/bolder than the desired font weight.

Applicable to buttons labels and page/post titles.
![image](https://cloud.githubusercontent.com/assets/11186313/9515088/9eb201ee-4cd1-11e5-938f-45d87de47b5e.png)

**Comment by isaq-titan** [comment]
Previously it was Merriweather - Bold (font-weight:regular)
but now it is updated to Merriweather - Regular (font-weight:bold)
