### ISSUE TITLE
Products page: Button label "View Product" isn't vertically centered in the container.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/WA-Marble-and-Granite#47]
![image](https://cloud.githubusercontent.com/assets/11186313/9515764/1d38e74a-4cd6-11e5-8014-3fa1097d44e8.png)

**Comment by isaq-titan** [comment]
It is done as per the design in PSD

![product-catalogue-view-products](https://cloud.githubusercontent.com/assets/13450822/9574640/29d9c344-4fe6-11e5-8f02-9e3bf8685fd7.jpg)

**Comment by roseliesromeo** [comment]
Can we enhance button label to be centered in the container as it is in some pages i.e, product listing page?
![image](https://cloud.githubusercontent.com/assets/11186313/9650034/bf0341fc-522f-11e5-86c4-03c046f8d7de.png)
