### ISSUE TITLE
Edge Details: Breadcrumbs layout and style is not consistent with other pages. There are extra bullets displayed.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/WA-Marble-and-Granite#66]
![image](https://cloud.githubusercontent.com/assets/11186313/9517305/b802a3dc-4ce1-11e5-9079-561c59d9d589.png)

**Comment by isaq-titan** [comment]
This needs edits in core code files and core code edits are restricted by Titan. Please advice.
