### ISSUE TITLE
General: Listed content overlaps the featured image.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/WA-Marble-and-Granite#77]
Applicable to single pages.
![image](https://cloud.githubusercontent.com/assets/11186313/9537539/3724a8ce-4d6c-11e5-9309-7226deacd1cc.png)

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/9651530/9d3c8348-5244-11e5-9955-6af702966ea3.png)

**Comment by isaq-titan** [comment]
I have checked this in various browsers and devices but it appears to be fine at my end, can you please be specific where exactly you are still this error. Thanks

**Comment by roseliesromeo** [comment]
IE
http://wamarble.stage.titanweb.com.au/care-and-maintenance/
http://wamarble.stage.titanweb.com.au/testimonials/
http://wamarble.stage.titanweb.com.au/testimonials/

**Comment by isaq-titan** [comment]
It is fixed now
