### ISSUE TITLE
Mobile - home page: it'd look good if we set the video to occupy the entire width.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/WA-Marble-and-Granite#78]
iPad air (portrait)
Applicable to Sidebar section

![image](https://cloud.githubusercontent.com/assets/11186313/9537987/260914d4-4d72-11e5-97a2-5e754d4a47a1.png)

**Comment by isaq-titan** [comment]
IVC Image will get stretched if set to full width as it is being cropped in the size same as shown above
