### ISSUE TITLE
Mobile - product single: It'd be better if the buttons have the same width.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/WA-Marble-and-Granite#79]
iPad air (portrait)
![image](https://cloud.githubusercontent.com/assets/11186313/9538029/8c35fba0-4d72-11e5-8bff-05034c3a6c20.png)

**Comment by isaq-titan** [comment]
The layout will be changed if the title of Enquire Now and View our range comes in single line when increased to full width - Please Advice
