### ISSUE TITLE
Mobile - Care&Maintenance: List view isn't centered in the screen.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/WA-Marble-and-Granite#88]
S4, iTouch 5
![image](https://cloud.githubusercontent.com/assets/11186313/9538634/2571fbb0-4d79-11e5-90e3-070572f2719c.png)

**Comment by roseliesromeo** [comment]
Not fixed in S4.
![image](https://cloud.githubusercontent.com/assets/11186313/9652408/9ed6b314-524d-11e5-8619-7e899e5322a7.png)

**Comment by roseliesromeo** [comment]
Not fixed for iTouch 5
![image](https://cloud.githubusercontent.com/assets/11186313/9681168/94244b16-532e-11e5-8994-a90d65392de7.png)

**Comment by isaq-titan** [comment]
It is fixed now
